### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by greper** [certd/certd#77]
- [x] web hook通知，邮件增加访问链接
- [x] unicloud 部署
- [x] 证书仓库，商业证书上传，获取证书api接口
- [x] 脚本部署
- [ ] 证书api接口sdk
- [x] 专业版邀请码，推荐奖励
- [ ] 商业版demo部署
- [x] 商业版用户套餐，用户支付，用户计费
- [x] 网站证书监控
- [x] 火山引擎dnsprovider，部署
- [x] namesilo支持
- [x] goddays
- [ ] nginx自动扫描部署脚本
- [ ] oauth2登录、iframe嵌入、商业版客服设置
- [x] mysql支持
- [x] 登录失败限制，短信登录、邮件注册
- [ ] 数据导入导出
- [ ] 实名认证
- [ ] 套餐卡密激活
- [x] 登录二次认证
- [x] 授权测试按钮
- [x] 在线编辑插件
- [ ] 插件商店
- [ ] 企业管理模式，全员管理员，项目管理

**Comment by XiaoPika** [comment]
需求申请：
1、证书自动部署至多吉云融合CDN（docs：https://docs.dogecloud.com/cdn/api-cert-upload）
2、证书自动部署至阿里云FC云函数（docs：https://help.aliyun.com/zh/functioncompute/developer-reference/api-fc-2023-03-30-struct-updatecustomdomaininput?spm=a2c4g.11186623.0.0.456e41944wVcov）

亚洲诚信上游取消了1年免费证书，国内自动更新部署SSL的需求以后只多不少，感谢大佬开发这么好的开源项目，略加打磨，比ohttps、httpsok等收费产品还好用。

**Comment by XiaoPika** [comment]
需求申请：
3、证书有效期监测，当有效期低于预设时间时，定期调用系统已配置的邮箱发送告警邮件

**Comment by greper** [comment]
> 需求申请： 3、证书有效期监测，当有效期低于预设时间时，定期调用系统已配置的邮箱发送告警邮件

1.29.2已支持

**Comment by a83988029** [comment]
我知道部署到到 unicloud 支持了，也能正常使用
想问下现在能否部署到 unicloud 里面的扩展存储的域名

**Comment by greper** [comment]
> 我知道部署到到 unicloud 支持了，也能正常使用 想问下现在能否部署到 unicloud 里面的扩展存储的域名

已支持
